
title: "Mijan Blog"
description: "Photos, memories, blogs & bookmarks."
baseurl: ""
url: ""

markdown: kramdown
permalink: /:categories/:title/

nav:
  - name: Home
    link: /
  - name: Gallery
    link: /gallery/
  - name: News
    link: /news/
  - name: Search
    link: /search/
  - name: About
    link: /about/
